spring.application.name=mi-youtube

# Configuración de OAuth2
spring.security.oauth2.client.registration.google.client-id=${FOCUSTUBE_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${FOCUSTUBE_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

server.forward-headers-strategy=framework
# Esto obliga a Spring a usar HTTPS en los enlaces de redirección de OAuth
server.tomcat.use-relative-redirects=true

youtube.api.key=${YOUTUBE_API_KEY}

server.port=${PORT:8080}